// ============================================================================
// AUTO-GENERATED FROM shared/strings.json — DO NOT EDIT MANUALLY
// Single Source of Truth: shared/strings.json
// Generator: scripts/sync_models.js
// Multilingual Parity: English (en), Hindi (hi), Gujarati (gu), Marathi (mr)
// Version: 1.2.0
// ============================================================================

import 'package:flutter/material.dart';

/// VanshaSetu — Sovereign Multilingual Public Infrastructure Localizations
/// Languages Supported: English (en), Hindi (hi), Gujarati (gu), Marathi (mr).
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const List<Locale> supportedLocales = [
    Locale('en'), // English
    Locale('hi'), // हिन्दी
    Locale('gu'), // ગુજરાતી
    Locale('mr'), // मराठी
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'VanshaSetu',
      'app_subtitle': 'Universal DPI Kinship & Identity Platform',
      'select_language': 'Select Language',
      'language_en': 'English',
      'language_hi': 'Hindi (हिन्दी)',
      'language_gu': 'Gujarati (ગુજરાતી)',
      'language_mr': 'Marathi (मराठी)',
      'nav_registration': 'Registration',
      'nav_lineage_canvas': 'Lineage Canvas',
      'nav_vansha_card': 'Vansha Card',
      'nav_demographics': 'Census Analytics',
      'nav_matrimony': 'Matrimony Engine',
      'nav_audit_logs': 'Audit Trail',
      'reg_title': 'New Citizen Registration',
      'reg_subtitle': 'Enter demographic and civil identity details',
      'first_name': 'First Name',
      'middle_name': 'Middle Name (Optional)',
      'last_name': 'Last Name',
      'gender': 'Gender',
      'dob': 'Date of Birth (YYYY-MM-DD)',
      'height_cm': 'Height (cm)',
      'weight_kg': 'Weight (kg)',
      'religion': 'Religion',
      'gotra': 'Gotra / Clan',
      'caste': 'Caste / Community',
      'category': 'Social Category',
      'blood_group': 'Blood Group',
      'marital_status': 'Marital Status',
      'address_line1': 'Address Line 1',
      'address_line2': 'Address Line 2 (Optional)',
      'pin_code': '6-Digit PIN Code',
      'district': 'District',
      'state': 'State',
      'country': 'Country',
      'autofill_gps': 'Auto-fill Live GPS',
      'submit_registration': 'Register Citizen & Generate VUID',
      'required_field': 'This field is mandatory',
      'invalid_pin': 'Enter a valid 6-digit Indian PIN code',
      'registration_success': 'Citizen successfully registered!',
      'canvas_title': 'Kinship Lineage Canvas',
      'recenter': 'Recenter',
      'add_kin': 'Add Kin',
      'search_vuid': 'Search 12-Digit VUID',
      'birth_event': 'Child Birth',
      'death_event': 'Civil Death',
      'marriage_event': 'Civil Marriage',
      'education_event': 'Education',
      'card_header': 'VANSHACARD • वन्श कार्ड',
      'republic_of_india': 'REPUBLIC OF INDIA / भारत गणराज्य',
      'vuid_label': 'VUID (VanshaSetu Universal ID)',
      'valid_throughout': 'Digital Public Infrastructure — Valid Throughout India',
      'share_whatsapp': 'Share on WhatsApp',
      'export_png': 'Save Image',
      'matrimony_title': 'Indian Matrimony Search',
      'matrimony_subtitle': 'Gotra Exogamy & Consanguinity Defense Engine',
      'looking_for': 'Looking For',
      'groom': 'Groom (वर)',
      'bride': 'Bride (वधू)',
      'age_range': 'Age Range',
      'seeker_gotra': 'Seeker Gotra',
      'sagotra_alert': 'Warning: Sagotra (Same Gotra)',
      'exogamous_permitted': 'Permitted: Exogamous Match',
      'search_candidates': 'Search Eligible Matches',
      'census_title': 'Demographics & Census Analytics',
      'census_subtitle': 'Real-Time Population Intelligence',
      'total_population': 'Total Population',
      'digital_verification_rate': 'Verified Identity Ratio',
      'filter_by_state': 'Filter by State',
      'filter_by_district': 'Filter by District',
      'gender_ratio': 'Gender Distribution',
      'age_pyramid': 'Age Cohort Pyramid',
      'audit_title': 'Immutable HIPAA & DPDP Audit Trail',
      'audit_verified': 'Cryptographic Blockchain Chain Intact',
      'audit_action': 'Action',
      'audit_timestamp': 'Timestamp',
      'audit_actor': 'Actor VUID',
      'verify_chain': 'Verify Integrity',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'loading': 'Processing...',
      'error': 'Error Occurred',
      'retry': 'Retry',
    },
    'hi': {
      'app_title': 'वन्शसेतु',
      'app_subtitle': 'सार्वभौमिक डिजिटल सार्वजनिक अवसंरचना वंशावली मंच',
      'select_language': 'भाषा चुनें',
      'language_en': 'English',
      'language_hi': 'हिन्दी',
      'language_gu': 'ગુજરાતી (गुजराती)',
      'language_mr': 'मराठी',
      'nav_registration': 'नागरिक पंजीकरण',
      'nav_lineage_canvas': 'वंशावली मानचित्र',
      'nav_vansha_card': 'वन्श कार्ड',
      'nav_demographics': 'जनगणना विश्लेषण',
      'nav_matrimony': 'विवाह मिलान',
      'nav_audit_logs': 'ऑडिट लॉग',
      'reg_title': 'नया नागरिक पंजीकरण',
      'reg_subtitle': 'जनसांख्यिकी एवं नागरिक पहचान विवरण दर्ज करें',
      'first_name': 'प्रथम नाम',
      'middle_name': 'मध्यम नाम (वैकल्पिक)',
      'last_name': 'उपनाम / जाति',
      'gender': 'लिंग',
      'dob': 'जन्म तिथि (YYYY-MM-DD)',
      'height_cm': 'ऊंचाई (सेमी)',
      'weight_kg': 'वजन (किग्रा)',
      'religion': 'धर्म',
      'gotra': 'गोत्र',
      'caste': 'जाति / समुदाय',
      'category': 'सामाजिक वर्ग',
      'blood_group': 'रक्त समूह',
      'marital_status': 'वैवाहिक स्थिति',
      'address_line1': 'पता पंक्ति 1',
      'address_line2': 'पता पंक्ति 2 (वैकल्पिक)',
      'pin_code': '6-अंकीय पिन कोड',
      'district': 'जिला',
      'state': 'राज्य',
      'country': 'देश',
      'autofill_gps': 'लाइव जीपीएस स्वतः भरें',
      'submit_registration': 'नागरिक पंजीकृत करें एवं VUID बनाएं',
      'required_field': 'यह जानकारी अनिवार्य है',
      'invalid_pin': 'मान्य 6-अंकीय पिन कोड दर्ज करें',
      'registration_success': 'नागरिक सफलतापूर्वक पंजीकृत!',
      'canvas_title': 'वंशावली मानचित्र (Lineage Canvas)',
      'recenter': 'केंद्र में लाएं',
      'add_kin': 'सम्बन्धी जोड़ें',
      'search_vuid': '12-अंकीय VUID खोजें',
      'birth_event': 'शिशु जन्म',
      'death_event': 'नागरिक मृत्यु',
      'marriage_event': 'विवाह पंजीकरण',
      'education_event': 'शिक्षा विवरण',
      'card_header': 'VANSHACARD • वन्श कार्ड',
      'republic_of_india': 'भारत गणराज्य / REPUBLIC OF INDIA',
      'vuid_label': 'VUID (वन्श पहचान संख्या)',
      'valid_throughout': 'डिजिटल पब्लिक इंफ्रास्ट्रक्चर — संपूर्ण भारत में मान्य',
      'share_whatsapp': 'व्हाट्सएप पर साझा करें',
      'export_png': 'छवि सुरक्षित करें',
      'matrimony_title': 'भारतीय विवाह मिलान मंच',
      'matrimony_subtitle': 'गोत्र बहिर्विवाह एवं सगोत्र सुरक्षा इंजन',
      'looking_for': 'प्रत्याशी की तलाश',
      'groom': 'वर (Groom)',
      'bride': 'वधू (Bride)',
      'age_range': 'आयु सीमा',
      'seeker_gotra': 'आवेदक का गोत्र',
      'sagotra_alert': 'चेतावनी: सगोत्र संबंध (समान गोत्र)',
      'exogamous_permitted': 'अनुमति: बहिर्विवाही अनुकूल मिलान',
      'search_candidates': 'योग्य प्रत्याशी खोजें',
      'census_title': 'जनसांख्यिकी एवं राष्ट्रीय जनगणना',
      'census_subtitle': 'रीयल-टाइम जनसंख्या विश्लेषण',
      'total_population': 'कुल जनसंख्या',
      'digital_verification_rate': 'सत्यापित पहचान अनुपात',
      'filter_by_state': 'राज्य अनुसार चुनें',
      'filter_by_district': 'जिला अनुसार चुनें',
      'gender_ratio': 'लिंगानुपात वितरण',
      'age_pyramid': 'आयु वर्ग पिरामिड',
      'audit_title': 'अपरिवर्तनीय HIPAA एवं DPDP ऑडिट ट्रेल',
      'audit_verified': 'क्रिप्टोग्राफिक ब्लॉकचेन श्रृंखला अक्षुण्ण है',
      'audit_action': 'कार्यवाही',
      'audit_timestamp': 'समय',
      'audit_actor': 'कर्ता VUID',
      'verify_chain': 'अखंडता सत्यापित करें',
      'cancel': 'रद्द करें',
      'confirm': 'पुष्टि करें',
      'loading': 'प्रक्रिया जारी है...',
      'error': 'त्रुटि हुई',
      'retry': 'पुनः प्रयास करें',
    },
    'gu': {
      'app_title': 'વંશસેતુ',
      'app_subtitle': 'સાર્વભૌમિક ડીપીઆઈ વંશાવળી અને નાગરિક ઓળખ મંચ',
      'select_language': 'ભાષા પસંદ કરો',
      'language_en': 'English (અંગ્રેજી)',
      'language_hi': 'हिन्दी (હિન્દી)',
      'language_gu': 'ગુજરાતી',
      'language_mr': 'मराठी (મરાઠી)',
      'nav_registration': 'નાગરિક નોંધણી',
      'nav_lineage_canvas': 'વંશાવળી નકશો',
      'nav_vansha_card': 'વંશ કાર્ડ',
      'nav_demographics': 'વસ્તી ગણતરી',
      'nav_matrimony': 'લગ્ન મેળવણી',
      'nav_audit_logs': 'ઓડિટ લૉગ્સ',
      'reg_title': 'નવી નાગરિક નોંધણી',
      'reg_subtitle': 'વસ્તી વિષયક અને નાગરિક ઓળખ વિગતો દાખલ કરો',
      'first_name': 'પ્રથમ નામ',
      'middle_name': 'પિતા/પતિનું નામ (વૈકલ્પિક)',
      'last_name': 'અટક / સરનેમ',
      'gender': 'જાતિ (લિંગ)',
      'dob': 'જન્મ તારીખ (YYYY-MM-DD)',
      'height_cm': 'ઊંચાઈ (સેમી)',
      'weight_kg': 'વજન (કિગ્રા)',
      'religion': 'ધર્મ',
      'gotra': 'ગોત્ર',
      'caste': 'જ્ઞાતિ / જાતિ',
      'category': 'સામાજિક વર્ગ',
      'blood_group': 'બ્લડ ગ્રૂપ (રક્ત જૂથ)',
      'marital_status': 'વૈવાહિક સ્થિતિ',
      'address_line1': 'સરનામું લીટી ૧',
      'address_line2': 'સરનામું લીટી ૨ (વૈકલ્પિક)',
      'pin_code': '૬-અંકનો પિન કોડ',
      'district': 'જિલ્લો',
      'state': 'રાજ્ય',
      'country': 'દેશ',
      'autofill_gps': 'લાઈવ જીપીએસ ઓટો-ફિલ',
      'submit_registration': 'નાગરિક નોંધણી કરો અને VUID મેળવો',
      'required_field': 'આ વિગત ભરવી ફરજિયાત છે',
      'invalid_pin': 'માન્ય ૬-અંકનો પિન કોડ દાખલ કરો',
      'registration_success': 'નાગરિકની સફળતાપૂર્વક નોંધણી થઈ ગઈ!',
      'canvas_title': 'વંશાવળી નકશો (Lineage Canvas)',
      'recenter': 'કેન્દ્રમાં લાવો',
      'add_kin': 'સંબંધી ઉમેરો',
      'search_vuid': '૧૨-અંકનો VUID શોધો',
      'birth_event': 'બાળ જન્મ',
      'death_event': 'મૃત્યુ નોંધણી',
      'marriage_event': 'લગ્ન નોંધણી',
      'education_event': 'શિક્ષણ વિગતો',
      'card_header': 'VANSHACARD • વંશ કાર્ડ',
      'republic_of_india': 'ભારત ગણરાજ્ય / REPUBLIC OF INDIA',
      'vuid_label': 'VUID (વંશ ઓળખ ક્રમાંક)',
      'valid_throughout': 'ડિજિટલ પબ્લિક ઇન્ફ્રાસ્ટ્રક્ચર — સમગ્ર ભારતમાં માન્ય',
      'share_whatsapp': 'વોટ્સએપ પર શેર કરો',
      'export_png': 'ઈમેજ સાચવો',
      'matrimony_title': 'ભારતીય વૈવાહિક સંબંધ શોધ',
      'matrimony_subtitle': 'ગોત્ર બહિર્વિવાહ અને સગોત્ર સંરક્ષણ પ્રણાલી',
      'looking_for': 'કોની શોધમાં છો?',
      'groom': 'વરરાજા (Groom)',
      'bride': 'કન્યા (Bride)',
      'age_range': 'ઉંમર મર્યાદા',
      'seeker_gotra': 'આવેદકનું ગોત્ર',
      'sagotra_alert': 'ચેતવણી: સગોત્ર સંબંધ (એક જ ગોત્ર)',
      'exogamous_permitted': 'માન્ય: બહિર્વિવાહ અનુકૂળ સંબંધ',
      'search_candidates': 'યોગ્ય મુરતિયા શોધો',
      'census_title': 'વસ્તી ગણતરી અને આંકડાશાસ્ત્ર',
      'census_subtitle': 'રીઅલ-ટાઇમ વસ્તી પૃથક્કરણ',
      'total_population': 'કુલ વસ્તી',
      'digital_verification_rate': 'પ્રમાણિત ઓળખ ગુણોત્તર',
      'filter_by_state': 'રાજ્ય પ્રમાણે ફિલ્ટર',
      'filter_by_district': 'જિલ્લા પ્રમાણે ફિલ્ટર',
      'gender_ratio': 'જાતિ ગુણોત્તર વિતરણ',
      'age_pyramid': 'વય જૂથ પિરામિડ',
      'audit_title': 'અપરિવર્તનીય HIPAA અને DPDP ઓડિટ રેકોર્ડ',
      'audit_verified': 'ક્રિપ્ટોગ્રાફિક બ્લોકચેન સાંકળ અખંડ છે',
      'audit_action': 'ક્રિયા / કાર્ય',
      'audit_timestamp': 'સમય',
      'audit_actor': 'કર્તા VUID',
      'verify_chain': 'સત્યતા ચકાસો',
      'cancel': 'રદ કરો',
      'confirm': 'પુષ્ટિ કરો',
      'loading': 'પ્રક્રિયા ચાલુ છે...',
      'error': 'ભૂલ આવી',
      'retry': 'ફરી પ્રયાસ કરો',
    },
    'mr': {
      'app_title': 'वंशसेतू',
      'app_subtitle': 'सार्वभौम डिजिटल सार्वजनिक पायाभूत सुविधा वंशावळ मंच',
      'select_language': 'भाषा निवडा',
      'language_en': 'English (इंग्रजी)',
      'language_hi': 'हिन्दी (हिंदी)',
      'language_gu': 'ગુજરાતી (गुजराती)',
      'language_mr': 'मराठी',
      'nav_registration': 'नागरिक नोंदणी',
      'nav_lineage_canvas': 'वंशावळ आलेख',
      'nav_vansha_card': 'वंश कार्ड',
      'nav_demographics': 'जनगणना विश्लेषण',
      'nav_matrimony': 'विवाह जुळवणी',
      'nav_audit_logs': 'ऑडिट नोंदी',
      'reg_title': 'नवीन नागरिक नोंदणी',
      'reg_subtitle': 'लोकसंख्या विषयक व ओळख माहिती प्रविष्ट करा',
      'first_name': 'पहिले नाव',
      'middle_name': 'वडिलांचे/पतीचे नाव (पर्यायी)',
      'last_name': 'आडनाव',
      'gender': 'लिंग',
      'dob': 'जन्मतारीख (YYYY-MM-DD)',
      'height_cm': 'उंची (सेमी)',
      'weight_kg': 'वजन (किग्रॅ)',
      'religion': 'धर्म',
      'gotra': 'गोत्र',
      'caste': 'जात / समुदाय',
      'category': 'सामाजिक प्रवर्ग',
      'blood_group': 'रक्तगट',
      'marital_status': 'वैवाहिक स्थिती',
      'address_line1': 'पत्ता ओळ १',
      'address_line2': 'पत्ता ओळ २ (पर्यायी)',
      'pin_code': '६-अंकी पिन कोड',
      'district': 'जिल्हा',
      'state': 'राज्य',
      'country': 'देश',
      'autofill_gps': 'थेट GPS द्वारे पत्ता भरा',
      'submit_registration': 'नागरिक नोंदणी करा व VUID मिळवा',
      'required_field': 'ही माहिती भरणे अनिवार्य आहे',
      'invalid_pin': 'योग्य ६-अंकी पिन कोड टाका',
      'registration_success': 'नागरिकाची यशस्वीरीत्या नोंदणी झाली!',
      'canvas_title': 'वंशावळ आलेख (Lineage Canvas)',
      'recenter': 'केंद्रीत करा',
      'add_kin': 'नातेवाईक जोडा',
      'search_vuid': '१२-अंकी VUID शोधा',
      'birth_event': 'अपत्य जन्म',
      'death_event': 'मृत्यू नोंदणी',
      'marriage_event': 'विवाह नोंदणी',
      'education_event': 'शिक्षण तपशील',
      'card_header': 'VANSHACARD • वंश कार्ड',
      'republic_of_india': 'भारतीय प्रजासत्ताक / REPUBLIC OF INDIA',
      'vuid_label': 'VUID (वंश ओळख क्रमांक)',
      'valid_throughout': 'डिजिटल पब्लिक इन्फ्रास्ट्रक्चर — संपूर्ण भारतात वैध',
      'share_whatsapp': 'व्हॉट्सॲपवर शेअर करा',
      'export_png': 'प्रतिमा जतन करा',
      'matrimony_title': 'भारतीय विवाह जुळवणी मंच',
      'matrimony_subtitle': 'गोत्र बहिर्विवाह व सगोत्र संरक्षण प्रणाली',
      'looking_for': 'कोणाचा शोध घेत आहात?',
      'groom': 'वर (Groom)',
      'bride': 'वधू (Bride)',
      'age_range': 'वय मर्यादा',
      'seeker_gotra': 'उमेदवाराचे गोत्र',
      'sagotra_alert': 'इशारा: सगोत्र संबंध (समान गोत्र)',
      'exogamous_permitted': 'मान्यताप्राप्त: बहिर्विवाही जुळणारा संबंध',
      'search_candidates': 'योग्य स्थळे शोधा',
      'census_title': 'लोकसंख्या व राष्ट्रीय जनगणना विश्लेषण',
      'census_subtitle': 'रिअल-टाइम लोकसंख्या सांख्यिकी',
      'total_population': 'एकूण लोकसंख्या',
      'digital_verification_rate': 'प्रमाणित ओळख प्रमाण',
      'filter_by_state': 'राज्यनुसार निवडा',
      'filter_by_district': 'જિલ્હ्यानुसार निवडा',
      'gender_ratio': 'लिंग गुणोत्तर प्रमाण',
      'age_pyramid': 'वयोगट पिरॅमिड',
      'audit_title': 'अपरिवर्तनीय HIPAA व DPDP ऑडिट नोंदी',
      'audit_verified': 'क्रिप्टोग्राफिक ब्लॉकचेन साखळी अभेद्य आहे',
      'audit_action': 'कृती / बदल',
      'audit_timestamp': 'वेळ',
      'audit_actor': 'कर्ता VUID',
      'verify_chain': 'अखंडता पडताळा',
      'cancel': 'रद्द करा',
      'confirm': 'नक्की करा',
      'loading': 'प्रक्रिया सुरू आहे...',
      'error': 'त्रुटी आढळली',
      'retry': 'पुन्हा प्रयत्न करा',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'gu', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
